services:
  app:
    build:
      args:
        user: edumanoel
        uid: 1000
      context: ./
      dockerfile: ./.docker/php/Dockerfile
    container_name: ${APP_NAME}_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - net

  db:
    image: mysql:5.7.28
    container_name: ${APP_NAME}_db
    restart: unless-stopped
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./.docker/repository/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - net

  nginx:
    image: nginx:1.19.10-alpine
    container_name: ${APP_NAME}_web
    restart: unless-stopped
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/
    networks:
      - net

networks:
  net:
    driver: bridge
